name: dino_run
description: A 2D infinite side scroller.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flame: ^1.32.0
  flame_audio: ^2.11.10
  hive: 2.2.3
  path_provider: 2.1.5
  provider: ^6.1.5+1
  cupertino_icons: 1.0.8
  rive: ^0.13.20
  flame_rive: ^1.10.12
  go_router: ^16.0.0
  collection: ^1.19.1
  google_fonts: ^6.3.1
  audioplayers: ^6.5.1
  flutter_soloud: ^3.3.6
  intl: ^0.20.2
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.6
  gap: ^3.0.1


dev_dependencies:
  hive_generator: 2.0.1
  build_runner: ^2.4.13
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  analyzer: ^5.13.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/backgrounds/character bg.png
    - assets/images/backgrounds/wood texture 01.png
    - assets/images/arrow - left.png
    - assets/images/arrow - right.png
    - assets/images/bg_square.png
    - assets/images/paper_bg.png
    - assets/images/background 2.png
    - assets/images/item_box.png
    - assets/images/back arrow.png
    - assets/images/background 2.png
    - assets/images/chapters.png
    - assets/images/circle.png
    - assets/images/Completed Menu.png
    - assets/images/correct logo.png
    - assets/images/Game Over Menu.png
    - assets/images/levels.png
    - assets/images/lock.png
    - assets/images/locked.png
    - assets/images/logo.png
    - assets/images/Paused Menu.png
    - assets/images/plank wood.png
    - assets/images/player profile.png
    - assets/images/Purchase.png
    - assets/images/question background.png
    - assets/images/settings.png

    - assets/images/backgrounds/
    - assets/images/parallax/
    - assets/images/parallax/forest/
    - assets/images/parallax/mountain/

    - assets/images/parallax/game_background_1/
    - assets/images/parallax/game_background_1/layers/

    - assets/images/parallax/game_background_2/
    - assets/images/parallax/game_background_2/layers/

    - assets/images/parallax/game_background_3/
    - assets/images/parallax/game_background_3/layers/

    - assets/images/parallax/game_background_4/
    - assets/images/parallax/game_background_4/layers/

    - assets/images/AngryPig/
    - assets/images/Bat/
    - assets/images/Rino/

    - assets/images/choices/

    - assets/images/shop_items/backgrounds/
    - assets/images/shop_items/items/
    - assets/images/shop_items/items/head/
    - assets/images/shop_items/items/eye/
    - assets/images/shop_items/items/shirt/

    - assets/audio/
    - assets/audio/bgm/ 
    - assets/audio/letters/
    - assets/audio/sound_effects/
    - assets/audio/questions_audio/en/
    - assets/audio/questions_audio/ceb/

    - assets/rive/
    - assets/translations/
    - assets/json/
    - assets/questions/

  fonts:
    # - family: Audiowide
    #   fonts:
    #     - asset: assets/fonts/Audiowide/Audiowide-Regular.ttf
    - family: LuckiestGuy
      fonts:
        - asset: assets/fonts/LuckiestGuy-Regular.ttf

# App Icon configuration
flutter_launcher_icons:
  android: "launcher_icon" # can be true, false, or a string like "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.png" 

# run this after:
# flutter pub run flutter_launcher_icons


# App Splash screen configuration 
flutter_native_splash:
  color: "#FFFFFF" # Your splash screen background color
  image: assets/images/app_icon.png # Your splash screen logo
  android: true
  # ios: true

# Run the package to create the native splash screen files
# flutter pub run flutter_native_splash:create